### ISSUE TITLE
Bootstrap bindings should have knife_config and @chef_config and config_content

### ISSUE THREAD

**Issue by ivey** [berkshelf/ridley#122]
Most official templates use knife_config and @chef_config. We should make sure those are available in the bindings so stock templates can be used. config_content instead of chef_config, too

**Comment by lamont-granquist** [comment]
bootstrapping seems to have been removed in ridley 2.0-ish sometime around this commit:  d278935ce7b223af5cd233c0067ac92d85ad7383
