### ISSUE TITLE
Add 'no_proxy' support.

### ISSUE THREAD

**Issue by chrisfarnham** [berkshelf/ridley#153]
I'm experiencing this issue with Berkshelf but assume that the issue really resides in ridley. I am behind a corporate firewall. When I perform a 'berks upload' it grabs the http_proxy and https_proxy settings from my .chef/knife.rb and uses those settings to correctly download cookbooks from the opscode site (e.g., apache2). However when it then begins to upload the cookbooks to my chef-server which is inside my firewall it fails. It is trying to use the fire wall when it shouldn't.

Here are my relevant knife.rb values with domains changed to protect the innocent:
http_proxy     "http://corpwall:80"
https_proxy    "http://corpwall:80"
no_proxy       "*corp.net,*intra,10.145.32.*"

**Comment by ehaselwanter** [comment]
still an issue here with

```
berks -v
3.2.3
```

does not honor `no_proxy` setting

**Comment by mickfeech** [comment]
Still an issue with 

```
berks -v 
4.0.1
```

When will this be included?

**Comment by turkenh** [comment]
+1 on this. 
I am also experiencing same issue and only the workaround setting/unsetting http_proxy mentioned above seems to work.

**Comment by mrmarbury** [comment]
setting and unsetting http_proxy/https_proxy won't work if you use a berkshelf-api server with supermarket and local backend. then you would need a proxy for the first half of the run and no proxy for the second half of the run. so berkshelf is unusable behind a proxy.
Still needing a fix here please
