### ISSUE TITLE
Scary messages from celluloid when exiting...

### ISSUE THREAD

**Issue by stensonb** [berkshelf/ridley#220]
Using Ridley 1.6.0 (and celluloid 0.15.2), I see some scary messages (from celluloid, I assume) when I'm done.  Here's the repro:

``` ruby
require 'ridley'
ridley = Ridley.from_chef_config '/Users/bryans/.chef/knife.rb'
ridley.cookbook.all.count
exit
```

yields this:

``` bash
W, [2013-10-07T14:05:37.346428 #32399]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:callwait
W, [2013-10-07T14:05:41.881098 #32399]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:callwait
W, [2013-10-07T14:05:42.484963 #32399]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:callwait
E, [2013-10-07T14:05:46.238594 #32399] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
```

Can I either:
1. pass in a logger to Ridley (to pass to celluloid) to quiet this down and/or
2. can I correctly "ridley.close" and cleanly "terminate all actors".

**Comment by b-slim** [comment]
Hi Guys i am still getting `[2015-06-01T14:43:25.676472 #29216] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!`.
i am using ridley (4.1.2) and celluloid (0.16.0)
celluloid-io (0.16.2).
I am i missing some fix ?
