### ISSUE TITLE
Nodes accessed via Ridley::NodeResource#all behave unexpectedly

### ISSUE THREAD

**Issue by jrab89** [berkshelf/ridley#237]
my_node = ridley.node.find('foo') # <Ridley::NodeObject chef_id:foo, ...>
    index = ridley.node.all.index(my_node)
    ridley.node.all[index] == my_node # true
    ridley.node.all[index].automatic == my_node.automatic # false

Ridley::NodeResource#all seems to provide access to the same node objects as Ridley::NodeResource#find, but calling methods like Ridley::NodeObject#automatic and Ridley::NodeObject#normal on nodes accessed through Ridley::NodeResource#all returns an empty hash.

**Comment by thommay** [comment]
Given this behaviour has existed for years, and as @reset says is intended, I think we'll close this bug since we won't fix it.
