### ISSUE TITLE
optionally delete /etc/chef/client.pem on bootstrap

### ISSUE THREAD

**Issue by aynleslie** [berkshelf/ridley#240]
Our bootstraps are not fail-proof, and we have reattempt logic built into our tools.  Ideally, we would be able to reuse the pem file on subsequent attempts, but with the change made by sha df431b6ede0e6, we cannot.  Currently, we have to delete the client and node in chef server first in order to repopulate the pem file.

I understand the use case for deleting it, but would you consider making that the default behavior with a means to optionally leave the pem file?

**Comment by thommay** [comment]
Closing as ridley-connectors is now separate.
