### ISSUE TITLE
load library folder recursively

### ISSUE THREAD

**Issue by sunruh** [berkshelf/ridley#303]
Chef 12 loads the libraries folder recursively, CHEF-672 is fixed by chef/chef#2129.

[lib/ridley/chef/cookbook.rb#L258](https://github.com/reset/ridley/blob/master/lib/ridley/chef/cookbook.rb#L258) should therefore also load this folder recursively.

**Comment by reset** [comment]
@sunruh absolutely, thanks for bringing this to my attention!

**Comment by PhilGrayson** [comment]
This has been fixed in dd539363 but a new tag hasn't been created since Oct 8.

Can a repo maintainer please push a new tag that includes this fix?

**Comment by tas50** [comment]
A new version has been released
