### ISSUE TITLE
Withdraw 4.4.0

### ISSUE THREAD

**Issue by mfischer-zd** [berkshelf/ridley#330]
Ridley made a backward-incompatible change in 4.4.0, removing an API method.  It should be withdrawn and replaced with Ridley 5.0.  See https://github.com/berkshelf/berkshelf/issues/1495

**Comment by reset** [comment]
Move the conversation here from https://github.com/berkshelf/berkshelf/issues/1495

/cc @jkeiser

**Comment by mjuarez** [comment]
Being bitten by this as well

**Comment by lamont-granquist** [comment]
do we just need to add method_missing handling to translate methods to hash lookups?

**Comment by mfischer-zd** [comment]
I recommend you withdraw this release first to help mitigate user impact.
Then you can concentrate on a fix.

**Comment by Soliah** [comment]
Yup just got bitten by this. All of a sudden CI started failing and I thought I was going crazy.

**Comment by Sliim** [comment]
:+1:

**Comment by b-dean** [comment]
It might be a good idea to have some specs for `Ridley::Chef::Config`so the build will fail when its API is broken.

**Comment by arieb** [comment]
+1

**Comment by erran-r7** [comment]
In the meantime pinning to ridley version v4.3.2 resolves issues related to not being able to call methods removed in #325. In my case `Ridley::Chef:: Config#chef_server_url` started failing several CI builds for me.

**Comment by err0** [comment]
This is bombing our chefspec CI tests as well.  +1 for a rollback.

**Comment by jkeiser** [comment]
Working on it! Will get a 4.4.1 without the proxy stuff, and get proper tests in and remerge when it works. Sorry!

**Comment by mfischer-zd** [comment]
I appreciate that you're working on a 4.4.1 release @jkeiser but in the interim, please remove 4.4.0 from the Rubygems servers so as not to further interrupt people's work.

**Comment by err0** [comment]
can you yank 4.4.0 in the interim? `gem yank ridley -v 4.4.0`

**Comment by jkeiser** [comment]
This is fixed: https://github.com/berkshelf/ridley/pull/331

We're trying not to yank things, it causes angst, the quick revert and release is intended to have the same effect.

**Comment by jkeiser** [comment]
Do respond or create more bugs if you are still having issues though!

**Comment by mfischer-zd** [comment]
There is far less angst to your customers for yanking buggy Gems than dealing with surprising failures.  By yanking them, you contain the damage window while you work on a fix.

**Comment by erran-r7** [comment]
> We're trying not to yank things, it causes angst — @jkeiser 

:+1: Glad you decided not to.

> There is far less angst to your customers for yanking buggy Gems than dealing with surprising failures. By yanking them, you contain the damage window while you work on a fix.

I disagree, CI in many of the above users cases caused their build to fail. Yanking could potentially require manual intervention to correct the build. Resolving this in the users gemfile/gemspec when the bad version existed was sufficient, in my opinion at least. Reverting and submitting a patch version that all of the above people would have pulled resolves issues for them and customers who would've pulled it later in the day.

**Comment by erran-r7** [comment]
> We're trying not to yank things, it causes angst — @jkeiser 

:+1: Glad you decided not to.

> There is far less angst to your customers for yanking buggy Gems than dealing with surprising failures. By yanking them, you contain the damage window while you work on a fix.

@mfischer-zd I disagree, CI in many of the above users cases caused their build to fail. Yanking could potentially require manual intervention to correct the build. Resolving this in the users gemfile/gemspec when the bad version existed was sufficient, in my opinion at least. Reverting and submitting a patch version that all of the above people would have pulled resolves issues for them and customers who would've pulled it later in the day.

**Comment by mfischer-zd** [comment]
@erran-r7 I think it depends on whether or not you're automatically running `bundle update` at every CI run.  We're not, as there's nothing to be gained by doing so when performing CI with Chef cookbooks.  Our bundles are locked, unless someone updates them manually. 

I imagine, or at least hope, that most users manage their cookbooks the same way.

**Comment by jkeiser** [comment]
@mfischer-zd I totally agree that we are responsible for clearing the broken release as quickly as possible, and we flubbed that (I wasn't checking mail and we didn't declare an incident). Sorry.

It's independent of whether to yank, however; a revert and re-release only costs us a few more minutes, gets more eyes on it, and causes less pain overall. The issue with time here was how long it took me to get *started*.

As for corrective action, I will be adding a run of the berkshelf master tests to catch this and any related regressions from happening in the future. It will turn super red before we ever release.

**Comment by mfischer-zd** [comment]
@jkeiser in this case the damage window was small, so thank you for the quick action.  However I would always yank first, fix later, in the case of severely buggy Gems.  There's no question that yanking will inconvenience some people who have already put the buggy version in their bundles, but I still contend that it will inconvenience fewer people overall.   If the Gem is no longer available, that gives me a very strong hint that I need to revert; OTOH, if things break with the new Gem, I then have to figure out the root cause, which could take significantly longer to determine -- your changes are mixed in with mine and I have to isolate the cause.

**Comment by kamaradclimber** [comment]
thanks @jkeiser  for your explaination.

**Comment by jkeiser** [comment]
FYI, I just re-released this with the relevant fixes in 4.4.2. Let me know if you see any issues; the berkshelf tests are working fine against it (really this time :). I'll watch the issue!

**Comment by RoboticCheese** [comment]
:heart:

**Comment by mjuarez** [comment]
Much thanks @jkeiser and all!
