### ISSUE TITLE
`berks upload` fails due to missing /sandboxes route in supermarket

### ISSUE THREAD

**Issue by zachsmorgan** [berkshelf/ridley#337]
In the latest version of supermarket the /sandboxes route does not exist and berks upload fails as a result.

**Comment by reset** [comment]
@zachsmorgan Ridley implement's the Chef Server's API, not the supermarket API. Did you mean the Chef Server API?

**Comment by zachsmorgan** [comment]
@reset  Yea, I was totally confused. Sorry!
