### ISSUE TITLE
ridley 4.6.1 not compatible with ruby 1.9 anymore

### ISSUE THREAD

**Issue by laradji** [berkshelf/ridley#363]

**Comment by laradji** [comment]
`
From e3182ccb521677faa12dccce04cb4001c4c777a4 Mon Sep 17 00:00:00 2001
From: Nacer Laradji <nacer.laradji@gmail.com>
Date: Tue, 15 Nov 2016 14:18:02 +0100
Subject: [PATCH] Fix Ruby 1.9.1 compatibility

---
 CHANGELOG.md   | 4 ++++
 ridley.gemspec | 2 +-
 2 files changed, 5 insertions(+), 1 deletion(-)

diff --git a/CHANGELOG.md b/CHANGELOG.md
index 2ddef78..f7a5bae 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,5 +1,9 @@
 # Ridley Changelog

+## 4.6.2
+
+- Force addressable version to 2.4.0 to keep compatibility with ruby 1.9.1
+
 ## 4.6.1

 - Pin to buff-ignore to ensure support for legacy Ruby releases. This will be the last release of Ridley that supports Ruby < 2.1.X. Pin accordingly if you require support for deprecated Ruby releases.
diff --git a/ridley.gemspec b/ridley.gemspec
index 7fb7738..5d16f5b 100644
--- a/ridley.gemspec
+++ b/ridley.gemspec
@@ -17,7 +17,7 @@ Gem::Specification.new do |s|
   s.version       = Ridley::VERSION
   s.required_ruby_version = ">= 1.9.1"

-  s.add_dependency 'addressable'
+  s.add_dependency 'addressable',             '~> 2.4.0'
   s.add_dependency 'varia_model',             '~> 0.4.0'
   s.add_dependency 'buff-config',             '~> 1.0'
   s.add_dependency 'buff-extensions',         '~> 1.0'
--
2.8.1

From df397923ebf29838baaa6408eed62b7b2236dbda Mon Sep 17 00:00:00 2001
From: Nacer Laradji <nacer.laradji@gmail.com>
Date: Tue, 15 Nov 2016 15:12:54 +0100
Subject: [PATCH] Change version

---
 lib/ridley/version.rb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lib/ridley/version.rb b/lib/ridley/version.rb
index 946008a..ae141ef 100644
--- a/lib/ridley/version.rb
+++ b/lib/ridley/version.rb
@@ -1,3 +1,3 @@
 module Ridley
-  VERSION = "4.6.1"
+  VERSION = "4.6.2"
 end
--
2.8.1
`

**Comment by laradji** [comment]
`From e3182ccb521677faa12dccce04cb4001c4c777a4 Mon Sep 17 00:00:00 2001
From: Nacer Laradji <nacer.laradji@gmail.com>
Date: Tue, 15 Nov 2016 14:18:02 +0100
Subject: [PATCH] Fix Ruby 1.9.1 compatibility

---
 CHANGELOG.md   | 4 ++++
 ridley.gemspec | 2 +-
 2 files changed, 5 insertions(+), 1 deletion(-)

diff --git a/CHANGELOG.md b/CHANGELOG.md
index 2ddef78..f7a5bae 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,5 +1,9 @@
 # Ridley Changelog

+## 4.6.2
+
+- Force addressable version to 2.4.0 to keep compatibility with ruby 1.9.1
+
 ## 4.6.1

 - Pin to buff-ignore to ensure support for legacy Ruby releases. This will be the last release of Ridley that supports Ruby < 2.1.X. Pin accordingly if you require support for deprecated Ruby releases.
diff --git a/ridley.gemspec b/ridley.gemspec
index 7fb7738..5d16f5b 100644
--- a/ridley.gemspec
+++ b/ridley.gemspec
@@ -17,7 +17,7 @@ Gem::Specification.new do |s|
   s.version       = Ridley::VERSION
   s.required_ruby_version = ">= 1.9.1"

-  s.add_dependency 'addressable'
+  s.add_dependency 'addressable',             '~> 2.4.0'
   s.add_dependency 'varia_model',             '~> 0.4.0'
   s.add_dependency 'buff-config',             '~> 1.0'
   s.add_dependency 'buff-extensions',         '~> 1.0'
--
2.8.1

From df397923ebf29838baaa6408eed62b7b2236dbda Mon Sep 17 00:00:00 2001
From: Nacer Laradji <nacer.laradji@gmail.com>
Date: Tue, 15 Nov 2016 15:12:54 +0100
Subject: [PATCH] Change version

---
 lib/ridley/version.rb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lib/ridley/version.rb b/lib/ridley/version.rb
index 946008a..ae141ef 100644
--- a/lib/ridley/version.rb
+++ b/lib/ridley/version.rb
@@ -1,3 +1,3 @@
 module Ridley
-  VERSION = "4.6.1"
+  VERSION = "4.6.2"
 end
--
2.8.1`

**Comment by thommay** [comment]
Ruby 1.9 went out of support over a year and a half ago: https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/ ; unfortunately we have neither time nor resources to work on unsupported rubies, and I'd strongly recommend that you update.

**Comment by laradji** [comment]
You only need to fix some gem version. I have a patch for 4.6.2 release

**Comment by laradji** [comment]
http://pastebin.com/x8ckH5Su

**Comment by laradji** [comment]
this should work

**Comment by laradji** [comment]
I understand the EOL thing and i'm not asking for supporting the last ridley version. But ridley 4.6.1 dont work anymore and it have work before. It's not very idempotent for system deployment.

  s.required_ruby_version = ">= 1.9.1"
