### ISSUE TITLE
Update client version

### ISSUE THREAD

**Issue by iancward** [berkshelf/ridley#374]
As part of a general effort to get folks to "get with the times", in our private chef installation, we'd like to prohibit chef client versions prior to 12.0.0. Unfortunately, Ridley (which Berkshelf uses) [masquerades as chef client version `11.4.0`](https://github.com/berkshelf/ridley/blob/36b43e93f57a7fc472e1e232de8a575bf6d9f305/lib/ridley.rb#L16) so berkshelf is getting blocked. This means we're unable to do things like use berks to upload cookbooks to the chef version.

Can we get this hard-coded version to be changed to something a bit more recent?

**Comment by scalp42** [comment]
@iancward curious how do you prevent user < 12.0.0. if you don't mind sharing?

**Comment by iancward** [comment]
@scalp42 it's a setting in private chef server:
`PrivateChef['lb']['chef_min_version'] = 12`

**Comment by iancward** [comment]
here's the relevant documentation: https://docs.chef.io/config_rb_server_optional_settings.html#lb-lb-internal

**Comment by haidangwa** [comment]
FYI, this is the line of code in question: https://github.com/berkshelf/ridley/blob/36b43e93f57a7fc472e1e232de8a575bf6d9f305/lib/ridley.rb#L16

**Comment by thommay** [comment]
Fixed by #377
