### ISSUE TITLE
Ridley gem for knife-vsphere

### ISSUE THREAD

**Issue by sethas** [berkshelf/ridley#376]
I am trying to use the Ridley api , to talk to vsphere.

I have knife-vsphere commands running on the cli , Would like to use it in my rails app, using ridley .

Can I do , ridley.vsphere.find("datastores") in my code?

**Comment by thommay** [comment]
Ridley is an api client for the chef server. It knows nothing about vsphere. 
knife-vsphere uses `vmomi` - https://github.com/vmware/rbvmomi . 

I'll be closing this, since it's not a ridley issue.
